name: Update Movies.m3u

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch movies.m3u from hosting and add notice
      env:
        FILE_URL: ${{ secrets.ONE_URL }}
      run: |
        curl -o original.m3u $FILE_URL

        # Add notice to beginning
        echo '# This m3u presented by https://t.me/ToufikOP' > movies.m3u
        echo '
        cat original.m3u >> movies.m3u
        rm original.m3u

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add movies.m3u
        git commit -m "Update DistroTV.m3u file." || echo "No changes to commit"

        git pull origin main --rebase
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:main
