name: Update movies m3u8 playlist

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ঘন্টায় একবার চলবে
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Fetch m3u8 links and save to root
        env:
          SOURCE_URL: ${{ secrets.ONE_URL }}
          OUTPUT_PATH: "movies_playlist.m3u8"
        run: |
          python - <<'PY'
          import re, os, sys, requests
          from urllib.parse import urljoin

          src = os.environ.get("SOURCE_URL")
          out = os.environ.get("OUTPUT_PATH")

          if not src:
              print("❌ Missing SOURCE_URL (set ONE_URL secret)", file=sys.stderr)
              sys.exit(1)

          try:
              r = requests.get(src, timeout=30)
              r.raise_for_status()
              text = r.text
          except Exception as e:
              print("❌ Failed to fetch source URL:", e, file=sys.stderr)
              sys.exit(1)

          urls = set()

          # Absolute links
          urls.update(re.findall(r'https?://[^\s"\'<>]+?\.m3u8', text, re.I))

          # Relative links
          for match in re.findall(r'["\']([^"\']+?\.m3u8)["\']', text, re.I):
              abs_url = urljoin(src, match)
              urls.add(abs_url)

          if not urls:
              print("⚠️ No .m3u8 links found.")
              open(out, "w").write("# No m3u8 found\n")
              sys.exit(0)

          with open(out, "w", encoding="utf-8") as f:
              f.write("# Source: {}\n".format(src))
              for u in sorted(urls):
                  f.write(u + "\n")

          print(f"✅ Saved {len(urls)} links to {out}")
          PY

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add movies_playlist.m3u8
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "update: movies m3u8 playlist (auto)"
            git push origin HEAD
          fi
