name: Update movies playlist

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ঘন্টায় একবার চলবে
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Fetch playlist and save to root
        env:
          SOURCE_URL: ${{ secrets.ONE_URL }}
          OUTPUT_PATH: "movies_playlist.m3u"
        run: |
          python - <<'PY'
          import os, sys, requests

          src = os.environ.get("SOURCE_URL")
          out = os.environ.get("OUTPUT_PATH")

          if not src:
              print("❌ Missing SOURCE_URL (set ONE_URL secret)", file=sys.stderr)
              sys.exit(1)

          try:
              r = requests.get(src, timeout=30)
              r.raise_for_status()
              text = r.text.strip()
          except Exception as e:
              print("❌ Failed to fetch source URL:", e, file=sys.stderr)
              sys.exit(1)

          if not text or "#EXTINF" not in text:
              print("⚠️ Source does not look like a valid M3U playlist.")
              sys.exit(0)

          with open(out, "w", encoding="utf-8") as f:
              f.write(text + "\n")

          print(f"✅ Playlist saved to {out} ({len(text.splitlines())} lines)")
          PY

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add movies_playlist.m3u
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "update: movies playlist (auto)"
            git push origin HEAD
          fi
