name: Update Tapmad Playlist

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ঘন্টায় একবার
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Fetch Tapmad playlist (raw save)
        env:
          SOURCE_URL: ${{ secrets.TWO_URL }}
          OUTPUT_PATH: "tapmad_playlist.m3u"
        run: |
          python - <<'PY'
          import os, sys, requests

          src = os.environ.get("SOURCE_URL")
          out = os.environ.get("OUTPUT_PATH")

          if not src:
              print("❌ Missing SOURCE_URL (set ONE_URL secret)", file=sys.stderr)
              sys.exit(1)

          try:
              # allow redirects; keep raw body (binary safe)
              r = requests.get(src, timeout=60, allow_redirects=True, headers={
                  "User-Agent": "Dalvik/2.1.0 (Linux; U; Android 10; IPTV-Player)"
              })
              r.raise_for_status()
              data = r.content
              print(f"✅ Fetched {len(data)} bytes from {src}")
          except Exception as e:
              print("❌ Failed to fetch:", e, file=sys.stderr)
              sys.exit(1)

          # Save as raw binary
          with open(out, "wb") as f:
              f.write(data)

          print(f"💾 Saved playlist to {out}")
          PY

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tapmad_playlist.m3u
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "update: tapmad playlist (auto)"
            git push origin HEAD
          fi
